package com.example.dogapitest.mvp.model.breedsModel

import android.os.Parcelable
import com.google.gson.annotations.Expose
import kotlinx.android.parcel.Parcelize

@Parcelize
data class Message (

	@Expose val affenpinscher : List<String>,
	@Expose val african : List<String>,
	@Expose val airedale : List<String>,
	@Expose val akita : List<String>,
	@Expose val appenzeller : List<String>,
	@Expose val australian : List<String>,
	@Expose val basenji : List<String>,
	@Expose val beagle : List<String>,
	@Expose val bluetick : List<String>,
	@Expose val borzoi : List<String>,
	@Expose val bouvier : List<String>,
	@Expose val boxer : List<String>,
	@Expose val brabancon : List<String>,
	@Expose val briard : List<String>,
	@Expose val buhund : List<String>,
	@Expose val bulldog : List<String>,
	@Expose val bullterrier : List<String>,
	@Expose val cairn : List<String>,
	@Expose val cattledog : List<String>,
	@Expose val chihuahua : List<String>,
	@Expose val chow : List<String>,
	@Expose val clumber : List<String>,
	@Expose val cockapoo : List<String>,
	@Expose val collie : List<String>,
	@Expose val coonhound : List<String>,
	@Expose val corgi : List<String>,
	@Expose val cotondetulear : List<String>,
	@Expose val dachshund : List<String>,
	@Expose val dalmatian : List<String>,
	@Expose val dane : List<String>,
	@Expose val deerhound : List<String>,
	@Expose val dhole : List<String>,
	@Expose val dingo : List<String>,
	@Expose val doberman : List<String>,
	@Expose val elkhound : List<String>,
	@Expose val entlebucher : List<String>,
	@Expose val eskimo : List<String>,
	@Expose val finnish : List<String>,
	@Expose val frise : List<String>,
	@Expose val germanshepherd : List<String>,
	@Expose val greyhound : List<String>,
	@Expose val groenendael : List<String>,
	@Expose val havanese : List<String>,
	@Expose val hound : List<String>,
	@Expose val husky : List<String>,
	@Expose val keeshond : List<String>,
	@Expose val kelpie : List<String>,
	@Expose val komondor : List<String>,
	@Expose val kuvasz : List<String>,
	@Expose val labrador : List<String>,
	@Expose val leonberg : List<String>,
	@Expose val lhasa : List<String>,
	@Expose val malamute : List<String>,
	@Expose val malinois : List<String>,
	@Expose val maltese : List<String>,
	@Expose val mastiff : List<String>,
	@Expose val mexicanhairless : List<String>,
	@Expose val mix : List<String>,
	@Expose val mountain : List<String>,
	@Expose val newfoundland : List<String>,
	@Expose val otterhound : List<String>,
	@Expose val ovcharka : List<String>,
	@Expose val papillon : List<String>,
	@Expose val pekinese : List<String>,
	@Expose val pembroke : List<String>,
	@Expose val pinscher : List<String>,
	@Expose val pitbull : List<String>,
	@Expose val pointer : List<String>,
	@Expose val pomeranian : List<String>,
	@Expose val poodle : List<String>,
	@Expose val pug : List<String>,
	@Expose val puggle : List<String>,
	@Expose val pyrenees : List<String>,
	@Expose val redbone : List<String>,
	@Expose val retriever : List<String>,
	@Expose val ridgeback : List<String>,
	@Expose val rottweiler : List<String>,
	@Expose val saluki : List<String>,
	@Expose val samoyed : List<String>,
	@Expose val schipperke : List<String>,
	@Expose val schnauzer : List<String>,
	@Expose val setter : List<String>,
	@Expose val sheepdog : List<String>,
	@Expose val shiba : List<String>,
	@Expose val shihtzu : List<String>,
	@Expose val spaniel : List<String>,
	@Expose val springer : List<String>,
	@Expose val stbernard : List<String>,
	@Expose val terrier : List<String>,
	@Expose val vizsla : List<String>,
	@Expose val waterdog : List<String>,
	@Expose val weimaraner : List<String>,
	@Expose val whippet : List<String>,
	@Expose val wolfhound : List<String>
) : Parcelable